


#include "PORT.h"

 const PORT_ConfigType User_Pins_cfg[NUMBER_OF_ACTIVATED_PINS] ={
	
		{PORT_PORTF , PORT_PIN1 , PORT_OUTPUT , PORT_DIO , PORT_PULLUP , PORT_PIN_CURR_8MA , PORT_LOW},
		{PORT_PORTF , PORT_PIN2 , PORT_OUTPUT , PORT_DIO , PORT_PULLUP , PORT_PIN_CURR_8MA , PORT_LOW},  
		{PORT_PORTF , PORT_PIN3 , PORT_OUTPUT , PORT_DIO , PORT_PULLUP , PORT_PIN_CURR_8MA , PORT_LOW} 

};
